version: "3.9"
services:
  # ===[ Postgres with PGVector ]=====================================================
  postgres:
    image: ankane/pgvector:v0.5.0
    ports:
      - 5432:5432
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
      - ./:/app-data
      - experiment-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
      - PGTZ=UTC
    command: >-
      postgres
        -c shared_preload_libraries='pg_stat_statements,auto_explain'
        -c pg_stat_statements.track=all
        -c pg_stat_statements.max=10000
        -c track_activity_query_size=4096
        -c auto_explain.log_analyze=true
        -c auto_explain.log_min_duration='3s'

# ===[ Volumes ]==============================================================
volumes:
  experiment-postgres-data:
    driver: local
